from copy import deepcopy
from pathlib import Path
import sys

from docx import Document


SOURCE = Path(sys.argv[1])
OUTPUT = Path(sys.argv[2])


def replace_paragraph(paragraph, text, style_name=None):
    paragraph.clear()
    if style_name is not None:
        paragraph.style = style_name
    paragraph.add_run(text)


def append_paragraph_after(anchor, text, style_name):
    document = anchor.part.document
    paragraph = document.add_paragraph()
    paragraph.style = style_name
    paragraph.add_run(text)
    anchor._element.addnext(paragraph._p)
    return paragraph


def prepend_paragraph_before(anchor, text, style_name):
    document = anchor.part.document
    paragraph = document.add_paragraph()
    paragraph.style = style_name
    paragraph.add_run(text)
    anchor._element.addprevious(paragraph._p)
    return paragraph


def add_table_row_like(table, source_row_index=1):
    new_tr = deepcopy(table.rows[source_row_index]._tr)
    table._tbl.append(new_tr)
    return table.rows[-1]


def set_cell_text(cell, text):
    cell.text = text


document = Document(SOURCE)
paragraphs = document.paragraphs

# Chapter 3: describe the completed evaluation procedure without placing results here.
replace_paragraph(
    paragraphs[248],
    "\tAI Evaluation Datasets and Scripts. To objectively evaluate the algorithmic performance of the system's artificial intelligence integrations prior to user testing, structured datasets and evaluation scripts were utilized. A curated dataset containing published guest reviews and predefined traveler preference profiles derived from SunnyTrips records served as the evaluation input. Automated evaluation scripts ran these datasets through the Gemini API and recommendation engine to compute specific AI performance metrics, including F1-Score, ROUGE, LLM-as-Judge scores, and Hit Rate.",
)
replace_paragraph(
    paragraphs[255],
    "\tAI Performance Metrics Computation. Before and during end-user evaluation, the algorithmic performance of the AI integrations was computed using established data-science metrics. The computations assessed sentiment classification performance, review-summarization textual similarity and semantic quality, and recommendation relevance.",
)
replace_paragraph(
    paragraphs[257],
    "\tROUGE Metrics (Review Summarization Evaluation). The abstractive review summaries generated by the Gemini AI were evaluated using ROUGE (Recall-Oriented Understudy for Gisting Evaluation). Each stored AI-generated hotel review summary was compared with a researcher-reviewed reference summary prepared from the corresponding guest-review set. ROUGE-1, ROUGE-2, and ROUGE-L precision, recall, and F1-scores were computed. ROUGE measured lexical overlap between the generated and reference summaries and was therefore used to assess textual similarity rather than as the sole measure of semantic correctness.",
)

llm_method = append_paragraph_after(
    paragraphs[257],
    "\tLLM-as-Judge Metrics (Review Summarization Evaluation). To complement ROUGE, an LLM-as-Judge procedure evaluated each stored AI-generated hotel review summary against the original published guest reviews in the database. The judge did not receive the researcher-reviewed reference summary. Each summary was assessed using a 4-point rubric across faithfulness, coverage, and conciseness. A score of 4 represented full satisfaction of the criterion, 3 represented mostly satisfactory performance with a minor issue, 2 represented partial performance with a material issue, and 1 represented failure to satisfy the criterion. Macro-average scores were computed across the evaluated hotels. This metric complemented ROUGE because an abstractive summary may preserve the source meaning while using wording that differs from the reference summary.",
    "normal",
)

# Replace internal drafting notes with visible placeholders for unfinished Chapter 4 content.
replace_paragraph(
    paragraphs[571],
    "[PLACEHOLDER: Verify and insert the final implemented sentiment categories and corresponding system evidence.]",
)
replace_paragraph(
    paragraphs[634],
    "[PLACEHOLDER: Insert the introductory narrative for the completed AI integration testing results.]",
)
replace_paragraph(
    paragraphs[636],
    "Metrics: [PLACEHOLDER: Insert final sentiment accuracy and F1-score.]",
)
replace_paragraph(
    paragraphs[637],
    "[PLACEHOLDER: Insert the sentiment-analysis results and discussion after the final evaluation is completed.]",
)
replace_paragraph(
    paragraphs[644],
    "Metric: [PLACEHOLDER: Insert final recommendation Hit Rate.]",
)
replace_paragraph(
    paragraphs[645],
    "[PLACEHOLDER: Insert the recommendation-effectiveness results and discussion after the final evaluation is completed.]",
)
replace_paragraph(
    paragraphs[648],
    "Metrics: [PLACEHOLDER: Insert final RAG faithfulness and answer-relevance scores.]",
)
replace_paragraph(
    paragraphs[649],
    "[PLACEHOLDER: Insert the RAG chatbot reliability results and discussion after the final evaluation is completed.]",
)
replace_paragraph(
    paragraphs[652],
    "[PLACEHOLDER: Insert feedback results after the remaining Agile iterations are completed.]",
)
replace_paragraph(
    paragraphs[692],
    "[PLACEHOLDER: Write the Chapter 4 summary after all results, feedback, and system refinements are finalized.]",
)
replace_paragraph(paragraphs[693], "")

# Chapter 4: retain actual review-summarization findings and keep interpretation under Discussion.
replace_paragraph(paragraphs[640], "Results", "Heading 3")
replace_paragraph(paragraphs[641], "")

review_table = document.tables[24]
prepend_paragraph_before(review_table, "Table X. Review Summarization Evaluation Results", "normal")
metrics = [
    ("ROUGE-1 F1", "0.4144"),
    ("ROUGE-2 F1", "0.0912"),
    ("ROUGE-L F1", "0.2296"),
    ("LLM-as-Judge Faithfulness (1-4)", "3.8421 / 4"),
    ("LLM-as-Judge Coverage (1-4)", "3.4211 / 4"),
    ("LLM-as-Judge Conciseness (1-4)", "3.9474 / 4"),
    ("LLM-as-Judge Overall Mean (1-4)", "3.7369 / 4"),
]

while len(review_table.rows) < len(metrics) + 1:
    add_table_row_like(review_table)

for row, (metric, result) in zip(review_table.rows[1:], metrics):
    set_cell_text(row.cells[0], metric)
    set_cell_text(row.cells[1], result)

results_text = append_paragraph_after(
    review_table,
    "The review-summarization evaluation covered 19 hotels. The macro-average ROUGE-1, ROUGE-2, and ROUGE-L F1-scores were 0.4144, 0.0912, and 0.2296, respectively. On the 1-4 LLM-as-Judge rubric, the macro-average scores were 3.8421 for faithfulness, 3.4211 for coverage, and 3.9474 for conciseness, with an overall mean of 3.7369.",
    "normal",
)
discussion_heading = append_paragraph_after(results_text, "Discussion", "Heading 3")
append_paragraph_after(
    discussion_heading,
    "The ROUGE scores show moderate overlap in individual terms and lower overlap in exact phrases and word order. This pattern is expected for abstractive summarization because the generated summary may convey the same review theme using different wording or a different sequence from the reference summary. The LLM-as-Judge results complement ROUGE by assessing the generated summary against the original published guest reviews. The faithfulness and conciseness scores indicate that the summaries were generally supported by the source reviews and were focused in form. Coverage received the lowest macro-average score, indicating that some summaries omitted recurring details or themes. The combined measures therefore support the use of abstractive review summarization while identifying coverage as an area for future refinement.",
    "normal",
)

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
document.save(OUTPUT)
